name: Nodejs Typescript CD

on:
  workflow_run:
    workflows: ["Check & Create PR"]
    types:
      - completed
  push:
    branches:
      - dev
      - homolog
      - prod

jobs:
  DeployToAWS:
    environment:
      name: ${{ github.ref }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          yarn
          cd iac
          npm install -g aws-cdk
          npm install

      - name: Setup AWS Credentials
        run: |
          echo "Configuring AWS Credentials"
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ vars.AWS_REGION }}
          aws configure set default.output json

      - name: Setting Environment Variables
        run: |
          echo "STAGE=${{ vars.STAGE }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ vars.AWS_REGION }}" >> $GITHUB_ENV
          echo "STACK_NAME=${{ vars.STACK_NAME }}${{ github.ref_name }}" >> $GITHUB_ENV
          echo "DYNAMO_TABLE_NAME=${{ vars.DYNA_DB_TABLE_NAME }}" >> $GITHUB_ENV
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: CDK Bootstrap
        run: |
          echo "Bootstrapping CDK"
          cd iac
          aws cloudformation describe-stacks --stack-name CDKToolkit 2>&1 > /dev/null || \
            cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ vars.AWS_REGION }}

      - name: Deploy with CDK
        run: |
          source $GITHUB_ENV
          yarn build
          cd iac
          cdk synth
          cdk deploy --require-approval never
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: ${{ vars.AWS_REGION }}
          STACK_NAME: ${{ vars.STACK_NAME }}${{ github.ref_name }}
          DYNAMO_TABLE_NAME: ${{ vars.DYNA_DB_TABLE_NAME }}

      - name: Cleanup
        run: |
          echo "Cleaning up temporary files"
          rm -rf node_modules
          rm -rf iac/node_modules
          rm -rf dist
